version: '3'
services:
  book:
    image: vvakame/review:5.8
    working_dir: /book
    volumes:
      - .:/book
    command: /bin/bash -ci "cd /book/articles && rake pdf"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
